### PR TITLE
introduce log parsing module and candump log pretty printer

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by BenGardiner** [comment]
@jeremydaily 
Here is an example pretty-printing of the Cybertruck candump log using `--format=true --candata=true`; using the DA converter in pull #1 on the 2013 J1939 DA

[example.pretty.log](https://github.com/nmfta-repo/pretty_j1939/files/3403251/example.pretty.log)

**Comment by jeremy-daily** [comment]
You may want to add an acknowledgements section and reference the NMFTA and NSF. I used the following in the CAN Logger 3 repo.
```
## Acknowledgements

This material is based upon work supported by the National Science Foundation under Grant No. 1715409. This project is in collaboration with the National Motor Freight Traffic Association (NMFTA). 
```

**Review by jeremy-daily — APPROVED** [review]
This looks like a good starting point. I'll try to exercise the scripts soon.

**Comment by BenGardiner** [comment]
These are now capable of extracting and printing SPNs from transport-level; both fixed and variable length; needs a JSON created with the code in #1 ; however, still fallsback to the old format . NB: that using the old format could result in incorrect parsing of SPNs that are used in multiple PGNs

**Pull request merged**
